[project]
name = "mimo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "toml>=0.10.2",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
